export interface SurveyActionTypes {
  type: SurveyActions;
  payload?: any;
}

export enum SurveyActions {
  GET_SURVEY = 'GET_SURVEY',
  SET_SURVEY = 'SET_SURVEY',
  CREATE_SURVEY = 'CREATE_SURVEY',
  CREATE_SURVEY_STATUS = 'CREATE_SURVEY_STATUS',
  UPDATE_SURVEY = 'UPDATE_SURVEY',
  DELETE_SURVEY = 'DELETE_SURVEY',
  GET_SURVEY_QUESTIONS = 'GET_SURVEY_QUESTIONS',
  SET_SURVEY_QUESTIONS = 'SET_SURVEY_QUESTIONS',
  GET_SURVEY_BY_ID = 'GET_SURVEY_BY_ID',
  SET_SURVEY_BY_ID = 'SET_SURVEY_BY_ID',
  CREATE_QUESTION = 'CREATE_QUESTION',
  UPDATE_QUESTION = 'UPDATE_QUESTION',
  DELETE_QUESTION = 'DELETE_QUESTION',
  GET_QUESTION_BY_ID = 'GET_QUESTION_BY_ID',
  SET_QUESTION_BY_ID = 'SET_QUESTION_BY_ID',
  CREATE_QUESTION_STATUS = 'CREATE_QUESTION_STATUS',
}
