export interface UserActionTypes {
  type: UserActions;
  payload?: any;
}
export enum UserActions {
  LOGOUT = "LOGOUT",
  SET_LOADER_FORM = "SET_LOADER_FORM",
  SET_FORM_ERRORS = "SET_FORM_ERRORS",
  USER_LOGIN_LODING = "USER_LOGIN_LODING",
  SET_USER_LODING = "SET_USER_LODING",
  SET_PROFILE_DATA = "SET_PROFILE_DATA",
  GET_PROFILE_DATA = "GET_PROFILE_DATA",
  USER_LOGIN = "USER_LOGIN",
  GET_USER_PROFILE_DATA = "GET_USER_PROFILE_DATA",
  SET_USER_PROFILE_DATA = "SET_USER_PROFILE_DATA",
  SET_OTP_DATA = "SET_OTP_DATA",
  ADD_PROFILE_IMAGE = "ADD_PROFILE_IMAGE",
  DELETE_PROFILE_IMAGE = "DELETE_PROFILE_IMAGE",
  EDIT_PROFILE_IMAGE_LOADER = "EDIT_PROFILE_IMAGE_LOADER",
  USER_LOGOUT = "USER_LOGOUT",
  SET_USERS =  "SET_USERS",
  GET_USERS = "GET_USERS",
  SET_USERS_DETAIL = "SET_USERS_DETAIL",
  GET_USERS_DETAIL = "GET_USERS_DETAIL",
  UPDATE_USER_STATUS = "UPDATE_USER_STATUS",
  SET_UPDATE_USER_STATUS = "SET_UPDATE_USER_STATUS",
  SET_USER_LOADER= "SET_USER_LOADER",
  GET_PAYMENT_DATA = "GET_PAYMENT_DATA",
  SET_PAYMENT_DATA = "SET_PAYMENT_DATA",
  SET_PAYMENT_DATA_LOADING = "SET_PAYMENT_DATA_LOADING",
  OTP_VERIFY = "OTP_VERIFY",
  RESEND_OTP = "RESEND_OTP",
  
  UPDATE_LAUNCH_TIME = 'UPDATE_LAUNCH_TIME',
  UPDATE_LAUNCH_TIME_LOADER = 'UPDATE_LAUNCH_TIME_LOADER',
  CREATE_GAME_LOADER = 'CREATE_GAME_LOADER',
  CREATE_GAME_STATUS = 'CREATE_GAME_STATUS',

  DELETE_GAME =  'DELETE_GAME',


  UPLOAD_EXCEL = 'UPLOAD_EXCEL',
  UPLOAD_EXCEL_STATUS = 'UPLOAD_EXCEL_STATUS',
  GET_CHEF = 'GET_CHEF',
  SET_CHEF = 'SET_CHEF',

}
